name: MicroHs CI

# Adapted from haskell-ci.yml and
# https://github.com/haskell/containers/blob/5669b01a/.github/workflows/mhs-ci.yml

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: MicroHs CI - Linux
    runs-on: ubuntu-24.04
    timeout-minutes:
      60
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          path: source
      - name: checkout mhs
        uses: actions/checkout@v6
        with:
          repository: augustss/MicroHs
          ref: v0.15.0.0
          path: mhs
      - name: make and install mhs
        run: |
          cd mhs
          make minstall
      - name: compile and install
        run: |
          PATH="$HOME/.mcabal/bin:$PATH"
          cd source
          mcabal -r install
      - name: cleanup
        run: |
          rm -rf "$HOME/.mcabal"
